リアクションを押して展開されたメッセージを消去する機能の追加
DiscordBotPortalJP/dispander pull request #24
Opened 2021-05-20 15:12 UTC by sizumita

リンク展開時に🗑リアクションをつけ、元メッセージの送信者とリンク送信者がリアクションをすると消せるようにしました。
メッセージリンクの引数を使って、外観を変えることなくデータを埋め込みました。

close #20

2021-05-20 20:07 UTC, sevenc-nanashi approved these changes

2021-05-21 23:17 UTC, Huyu2239 commented on dispander/module.py
> +async def delete_dispand_messages_by_reaction(bot: discord.Client, payload_or_reaction, user=None):
関数名と引数名が長いので、関数名はdelete_dispand、
引数をキーワードにして可読性上げた方がいいとおもいます
(初レビューなので場違いだったら教えてください)

2021-05-22 13:01 UTC, sizumita commented on dispander/module.py
> +async def delete_dispand_messages_by_reaction(bot: discord.Client, payload_or_reaction, user=None):
対応しましたが、どうでしょう？

2021-05-22 14:13 UTC, Huyu2239 commented on dispander/module.py
> +async def delete_dispand_messages_by_reaction(bot: discord.Client, payload_or_reaction, user=None):
最高です
ありがとうございます

2021-05-22 15:45 UTC, Huyu2239 commented on dispander/module.py
> +    base_url_match = re.match(regex_discord_message_url + regex_extra_url, url)
デバックしてみたのですが、
 author.urlの&extra=が空の際に、base_url_matchがNoneとなり、base_url_match.groupdict()でエラーが起きます

AttributeError: 'NoneType' object has no attribute 'groupdict'

2021-05-23 00:56 UTC, sizumita commented on dispander/module.py
> +    base_url_match = re.match(regex_discord_message_url + regex_extra_url, url)
あーそれは考慮し忘れていました

2021-05-23 08:18 UTC, sizumita commented on dispander/module.py
> +    base_url_match = re.match(regex_discord_message_url + regex_extra_url, url)
修正しました

2021-05-23 10:27 UTC, sevenc-nanashi requested changes

2021-05-23 10:27 UTC, sevenc-nanashi commented on README.md
> +展開したメッセージを消去する機能を使用するには`on_reaction_add`イベントもしくは`on_raw_reaction_add`イベントのどちらかでdelete_dispand関数を実行してください。
```suggestion
展開したメッセージを消去する機能を使用するには`on_reaction_add`イベントもしくは`on_raw_reaction_add`イベントのどちらかでdelete_dispand関数を実行してください。
on_raw_reaction_addの場合はキーワード引数`payload`にRawReactionActionEventを、on_reaction_addの場合はキーワード引数`user`にUser、`reaction`にReactionを指定して下さい。```
少し詳しくした方が良いのでは？

2021-05-23 10:31 UTC, Huyu2239 commented
使う側が`DELETE_REACTION_EMOJI`を指定できるようにできたらもっといいかと思います
✖リアクションにしたい場合とか

2021-05-23 10:33 UTC, sevenc-nanashi commented
#22 じっそうするならここらへんになりそう

2021-05-23 11:32 UTC, sizumita commented
作ってみましたがどうですか

2021-05-24 15:02 UTC, Huyu2239 commented
なるほど
LGTM.

2021-05-25 13:21 UTC, sevenc-nanashi commented
ふと思ったけど環境変数に絵文字って入れられるの…？

2021-05-25 14:58 UTC, sizumita commented
試してから聞いて欲しかったんですが、Unicodeならなんでも入れられると思います...

2021-05-25 21:20 UTC, sevenc-nanashi approved these changes

2021-05-26 05:43 UTC, chun37 commented on dispander/module.py
> +                         user: Optional[discord.User] = None):
```suggestion
                         user: Optional[discord.User] = None) -> None:
```
引数に型ヒントがあって、返り値に型ヒントが無いのは何故？

2021-05-26 05:43 UTC, chun37 commented on dispander/module.py
> +        if user.id == bot.user.id:
user が None だった時の検証は入れないんですか？

2021-05-26 05:43 UTC, chun37 commented on dispander/module.py
> +    return "{0.jump_url}?base_aid={1.id}&aid={2.id}&extra={3}".format(
discord.Message.jump_url は 1.7 から実装されていますが、dispandar 自体は 1.3 以上を必須としています。
1.7 未満を使用した場合、ここでエラーが発生すると思います。

2021-05-26 05:43 UTC, chun37 commented on dispander/module.py
> +        url=message.jump_url
ここも 1.7 未満に jump_url が実装されていない

2021-05-26 07:28 UTC, Lapis256 commented on dispander/module.py
> +    return "{0.jump_url}?base_aid={1.id}&aid={2.id}&extra={3}".format(
https://github.com/Rapptz/discord.py/blob/v1.3.3/discord/message.py#L608
discord.Message.jump_urlは1.3.3の頃からありますよ

2021-05-26 07:32 UTC, chun37 commented on dispander/module.py
> +    return "{0.jump_url}?base_aid={1.id}&aid={2.id}&extra={3}".format(
わ、本当だ
https://github.com/Rapptz/discord.py/blob/f56543df15a17434689542f227f466608739e865/discord/message.py#L437

> versionadd:: 1.7

と書いてあったので、1.7 で追加されたと認識してました

2021-05-26 07:44 UTC, Lapis256 commented on dispander/module.py
> +    return "{0.jump_url}?base_aid={1.id}&aid={2.id}&extra={3}".format(
それは、discord.MessageReference.jump_url なので…

2021-05-26 07:46 UTC, chun37 commented on dispander/module.py
> +    return "{0.jump_url}?base_aid={1.id}&aid={2.id}&extra={3}".format(
あ…………w
失礼しました

2021-05-26 07:54 UTC, sizumita commented on dispander/module.py
> +        if user.id == bot.user.id:
それはエラーになるだけなのでいらないと思います

2021-05-26 07:55 UTC, sizumita commented on dispander/module.py
> +                         user: Optional[discord.User] = None):
わかりにくかったところにつけてあるだけです
ライブラリの方針としてもつけてなさそうなのでいらないかなと

2021-05-29 05:31 UTC, Huyu2239 commented on dispander/module.py
> +        main_message = sent_messages.pop(0)
popはリストを丸ごと書き換えるから避けたほうがいいと教えてもらったんですが、[L88](https://github.com/DiscordBotPortalJP/dispander/blob/f7a0f0592acd8a2912aa51fa10c09de4d8769490/dispander/module.py#L98)の変数をそのままそのままmain_messageとすればいいのではないでしょうか

2021-05-29 08:07 UTC, sizumita commented on dispander/module.py
> +        main_message = sent_messages.pop(0)
popの話とL88の話は全く関係ないと思いますが、embedだけのメッセージだったときにうまく処理ができなくなるのでだめだと思います。
また、先頭のメッセージも使うのでpopがいいと思っていますが、

```python
main_message, *others = sent_messages
```
の方が良いと思いますかね？

2021-05-29 09:38 UTC, Huyu2239 commented on dispander/module.py
> +        main_message = sent_messages.pop(0)
あそっか
引用先がembedだったらそのまま送るんでしたっけ
なら関係ないですね失礼

2021-06-20 15:02 UTC, 1ntegrale9 approved these changes
大変遅くなって申し訳ないですが、
動作確認まで済んでいるのでApproveします。

（ただしどこかでリファクタリングは必須）

2021-06-20 15:03 UTC, merged