Discord.py v2.0 におけるエラー修正
DiscordBotPortalJP/dispander pull request #41
Opened 2022-11-23 16:29 UTC by npostring

v2.0 (正確には現最新版のv2.1) を動かした際にエラーとなっていた部分を修正しました。

2022-11-23 16:33 UTC, sizumita requested changes

2022-11-23 16:33 UTC, sizumita commented on dispander/module.py
> +        icon_url=message.author.avatar,
Optionalなのでfallback avatar urlもprでつけた方がいい気がします

2022-11-23 16:33 UTC, sizumita commented on dispander/module.py
> +        icon_url=message.guild.icon,
こちらも

2022-11-23 17:05 UTC, npostring commented
ちょっと各メソッドのリファレンス見ても不明だったんですが、fallbackってどう設定すれば良いですかね…？
(名前からするにurl先が見つからなかった際のデフォルト画像設定？)

2022-11-23 17:11 UTC, sizumita commented
あ、そうですね、Noneだった場合のデフォルト値って感じです
`discord.DefaultAvatar.red`あたりでいいんじゃないかなと

2022-11-26 04:09 UTC, npostring commented
修正しましたがこんな感じで大丈夫でしょうか？
https://github.com/npostring/dispander/blob/13feb09b76b3bed5fef819ab597a28931f016437/dispander/module.py#L174
https://github.com/npostring/dispander/blob/13feb09b76b3bed5fef819ab597a28931f016437/dispander/module.py#L179

URL指定はdiscord.pyのasset.pyを参考にしました。
https://github.com/Rapptz/discord.py/blob/66d85007b7727403b6d7cacf8be9e2fc38b72c24/discord/asset.py#L222

2022-11-26 05:00 UTC, sizumita commented on dispander/module.py
> +        icon_url=message.author.avatar if message.author.avatar is not None else f'{discord.Asset.BASE}/embed/avatars/{discord.DefaultAvatar.red}.png',
Optionalなので`message.author.avatar or f'...'`でもいいんじゃないかなと思います

2022-11-26 05:00 UTC, sizumita commented on dispander/module.py
> +        icon_url=message.guild.icon if message.guild.icon is not None else f'{discord.Asset.BASE}/embed/avatars/{discord.DefaultAvatar.red}.png',
こちらも

2022-11-26 05:54 UTC, npostring commented
このorの使い方初めて知りました。めっちゃ便利……。
こちらでどうでしょう。

https://github.com/npostring/dispander/blob/ac684d30d51087cb5c1302471670f4a75b94b875/dispander/module.py#L174
https://github.com/npostring/dispander/blob/ac684d30d51087cb5c1302471670f4a75b94b875/dispander/module.py#L179

2022-11-26 08:01 UTC, sizumita approved these changes
僕はいいと思います。
@1ntegrale9 マージした後のバージョンアップお願いします

2022-11-26 09:56 UTC, Nirezi approved these changes
LGTM.

2023-01-27 17:08 UTC, merged

2023-01-27 17:09 UTC, 1ntegrale9 commented
LGTM
対応が大変遅れて申し訳ありません 🙏